defaults:
  - WGA

handler: SampleEarlyStopWGAIrreversible

args:
  dataloader_drop_last: false

method_args:
  warm_up: 1
  gain_threshold: 1.0
  patience: 1
  rebound_delta: 0.1
  reactivation_patience: 2
  initial_nll_cache_path: null
